Search for new entries meanwhile ${x} is in-copy

diff --git a/skilcrypt-daemon b/skilcrypt-daemon
--- a/skilcrypt-daemon
+++ b/skilcrypt-daemon
@@ -25,7 +25,7 @@ PASSWORD_FILE='/tmp/pws'
 
 ### Don't touch anything below this line ###
 [[ ! -d "${SOURCE_FILES}" ]] && mkdir --mode=700 "${SOURCE_FILES}"
-[[ ! -f "${PASSWORD_FILE}" ]] && exit 1
+[[ ! -f "${PASSWORD_FILE}" ]] && { printf '%s\n' 'Missing password file'; exit 1 ;}
 declare -a _check_lockfile_db1
 declare -a _check_lockfile_db2
 declare -a _file_in_copy_arr
@@ -53,9 +53,10 @@ do
         find "${SOURCE_FILES}" -type f ! -name "*.gpg" | {
             while read x
             do
-                x=${x/\/}
+                x="${x/\/}"
 
-                _lock_file="/tmp/${x##*/}-lockfile"
+                _lock_file="${x//\//.}"
+                _lock_file="/tmp/${_lock_file// /.}-lock"
 
                 # Deleted files -> catch 'em
                 [[ ! -f "${x}" ]] && continue
@@ -67,34 +68,30 @@ do
                     __is_file_in_copy 'db2'  "${x}"
 
                     [[ " ${_check_lockfile_db1[@]} " =~ " ${_check_lockfile_db2[@]} " ]] \
-                        && {
-                            rm -rf "${_lock_file}"
-                            apollo=''
-                    } || apollo='return to home'
+                        && rm -rf "${_lock_file}" || continue
+                } || {
+
+                    _orig_size=$(stat -c %s "${x}")
+
+                    # Is ${x} in-copy progress ?
+                    for z in {1..5}
+                    do
+                        sleep 0.2
+                        _new_size[${z}]=$(stat -c %s "${x}")
+                    done
+
+                    [[ ! " ${_new_size[@]} " =~ " ${_orig_size} " ]] && {
+                        touch "${_lock_file}"
+                        continue
+                    }
+
+                    gpg --batch --quiet --yes --passphrase-file "${PASSWORD_FILE}" \
+                    --cert-digest-algo SHA512 --cipher-algo AES256 \
+                    --digest-algo SHA512 --s2k-cipher-algo AES256 --s2k-digest-algo SHA512 \
+                    --s2k-mode 3 --s2k-count 64981052 --compress-algo 0 --symmetric "${x}"
+
+                    rm -rf "${x}"
                 }
-
-                [[ ! -z "${apollo}" ]] && continue
-
-                _orig_size=$(stat -c %s "${x}")
-
-                # Is ${x} in-copy progress ?
-                for z in {1..5}
-                do
-                    sleep 0.2
-                    _new_size[${z}]=$(stat -c %s "${x}")
-                done
-
-                [[ ! " ${_new_size[@]} " =~ " ${_orig_size} " ]] && {
-                    touch "${_lock_file}"
-                    continue
-                }
-
-                gpg --batch --quiet --yes --passphrase-file "${PASSWORD_FILE}" \
-                --cert-digest-algo SHA512 --cipher-algo AES256 \
-                --digest-algo SHA512 --s2k-cipher-algo AES256 --s2k-digest-algo SHA512 \
-                --s2k-mode 3 --s2k-count 64981052 --compress-algo 0 --symmetric "${x}"
-
-                rm -rf "${x}"
 
             done
         }
